# 학습이 잘 되는 모델

사용할 레이어
- `tf.keras.layers.BatchNormalization()`
- `tf.keras.layers.Activation('swish')`

## Boston

In [7]:
import pandas as pd
import tensorflow as tf

boston = pd.read_csv('boston.csv')
indep = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
dep = boston[['medv']]
print(indep.shape, dep.shape)

(506, 13) (506, 1)


In [3]:
X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(10)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(10)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(10)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [4]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                140       
_________________________________________________________________
batch_normalization_1 (Batch (None, 10)                40        
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                110       
_________________________________________________________________
batch_normalization_2 (Batch (None, 10)                40        
_________________________________________________________________
activation_2 (Activation)    (None, 10)                0   

In [8]:
model.fit(indep,dep,epochs=1000, verbose=0)
model.fit(indep,dep,epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 9.3409
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 11.3333
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 11.4857
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 10.2811
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 9.1542
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 9.8176
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 10.8834
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 11.7544
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 11.4008
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 10.7238


In [ ]:
print(model.predict(indep[:5]))
print(dep[:5])

## Iris

In [9]:
import pandas as pd
import tensorflow as tf

iris = pd.read_csv('iris.csv')
encoding = pd.get_dummies(iris)
encoding.head()

indep = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep = encoding[[ '품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(indep.shape, dep.shape)

(150, 4) (150, 3)


In [11]:
X = tf.keras.layers.Input(shape=[4])

H = tf.keras.layers.Dense(5)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(5)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(5)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',  metrics='accuracy')

In [12]:
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_9 (Dense)              (None, 5)                 25        
_________________________________________________________________
batch_normalization_7 (Batch (None, 5)                 20        
_________________________________________________________________
activation_6 (Activation)    (None, 5)                 0         
_________________________________________________________________
dense_10 (Dense)             (None, 3)                 18        
Total params: 63
Trainable params: 53
Non-trainable params: 10
_________________________________________________________________


In [13]:
model.fit(indep,dep,epochs=200)

Epoch 1/200
5/5 [==============================] - 1s 4ms/step - loss: 1.1296 - accuracy: 0.3757
Epoch 2/200
5/5 [==============================] - 0s 2ms/step - loss: 1.0870 - accuracy: 0.3570
Epoch 3/200
5/5 [==============================] - 0s 3ms/step - loss: 1.0828 - accuracy: 0.4207
Epoch 4/200
5/5 [==============================] - 0s 2ms/step - loss: 1.0805 - accuracy: 0.3843
Epoch 5/200
5/5 [==============================] - 0s 2ms/step - loss: 1.0234 - accuracy: 0.4578
Epoch 6/200
5/5 [==============================] - 0s 2ms/step - loss: 1.0245 - accuracy: 0.4990
Epoch 7/200
5/5 [==============================] - 0s 2ms/step - loss: 1.0286 - accuracy: 0.5109
Epoch 8/200
5/5 [==============================] - 0s 2ms/step - loss: 0.9978 - accuracy: 0.6004
Epoch 9/200
5/5 [==============================] - 0s 2ms/step - loss: 1.0155 - accuracy: 0.5677
Epoch 10/200
5/5 [==============================] - 0s 2ms/step - loss: 0.9994 - accuracy: 0.6448
Epoch 11/200
5/5 [===========

In [14]:
print(model.predict(indep[:5]))
print(dep[:5])

[[9.9926454e-01 6.3928135e-04 9.6097676e-05]
 [9.9387580e-01 5.6365589e-03 4.8771864e-04]
 [9.9749869e-01 2.2840234e-03 2.1727178e-04]
 [9.8828018e-01 1.1081832e-02 6.3799851e-04]
 [9.9941301e-01 5.1160890e-04 7.5396347e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
