# Hidden Layer

Hidden Layer : Input Layer와 Output Layer사이에 위치한 Layer  
코드상의 구현으로는 전까지 output부분을 생성하는 Dense에 출력값의 수와 입력 변수를 적는 것에 `activation='swish'`를 통해 swish 함수를 사용하는 것이 추가된 형태이다.

## 보스턴 집값 예측

In [3]:
import pandas as pd
import tensorflow as tf

boston = pd.read_csv('boston.csv')
indep = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
dep = boston[['medv']]
print(indep.shape, dep.shape)

(506, 13) (506, 1)


In [9]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [10]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.fit(indep,dep,epochs=1000, verbose=0)
model.fit(indep,dep,epochs=10)


Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 17.5534
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 18.5521
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 19.3837
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 17.7919
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 18.7920
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 17.7916
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 18.4803
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 18.7123
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 17.9515
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 18.6683


In [12]:
print(model.predict(indep[:5]))
print(dep[:5])

[[26.74765 ]
 [22.837503]
 [29.276546]
 [29.78014 ]
 [29.674809]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


## 아이리스 품종 분류

In [14]:
import pandas as pd
import tensorflow as tf

iris = pd.read_csv('iris.csv')
encoding = pd.get_dummies(iris)
encoding.head()

indep = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep = encoding[[ '품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(indep.shape, dep.shape)

(150, 4) (150, 3)


In [15]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(5, activation='swish')(X)
H = tf.keras.layers.Dense(5, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',  metrics='accuracy')

In [19]:
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_7 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_8 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 18        
Total params: 73
Trainable params: 73
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.fit(indep,dep,epochs=200)

Epoch 1/200
5/5 [==============================] - 1s 4ms/step - loss: 1.1618 - accuracy: 0.3394
Epoch 2/200
5/5 [==============================] - 0s 2ms/step - loss: 1.1295 - accuracy: 0.3368
Epoch 3/200
5/5 [==============================] - 0s 2ms/step - loss: 1.1102 - accuracy: 0.3303
Epoch 4/200
5/5 [==============================] - 0s 2ms/step - loss: 1.1348 - accuracy: 0.3419
Epoch 5/200
5/5 [==============================] - 0s 2ms/step - loss: 1.1041 - accuracy: 0.5389
Epoch 6/200
5/5 [==============================] - 0s 2ms/step - loss: 1.0852 - accuracy: 0.6775
Epoch 7/200
5/5 [==============================] - 0s 2ms/step - loss: 1.0907 - accuracy: 0.6528
Epoch 8/200
5/5 [==============================] - 0s 2ms/step - loss: 1.0656 - accuracy: 0.6866
Epoch 9/200
5/5 [==============================] - 0s 3ms/step - loss: 1.0636 - accuracy: 0.6658
Epoch 10/200
5/5 [==============================] - 0s 2ms/step - loss: 1.0496 - accuracy: 0.6745
Epoch 11/200
5/5 [===========

In [18]:
print(model.predict(indep[:5]))
print(dep[:5])

[[9.9819928e-01 5.6004950e-07 1.8001288e-03]
 [9.9541795e-01 4.4927519e-06 4.5775687e-03]
 [9.9731535e-01 2.0992356e-06 2.6825424e-03]
 [9.9582267e-01 6.7909036e-06 4.1705309e-03]
 [9.9846494e-01 4.4651722e-07 1.5346654e-03]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
